### PR TITLE
Make partitions for SLURM configurable. Resolve #29. 

### LINKED ISSUE #29: SLURM queue names
Don't assume the queue names, get them from the configuration.
https://github.com/WIPACrepo/pyglidein/blob/master/submit.py#L277

### PR DESCRIPTION
**Pull request by briedel**

### CODE REVIEW

**Comment by dsschult** [comment]
I'm not sure the cleanup code is generalized enough - it seems specific to one batch system.

But I will take the last two commits as a valid solution to #29.

**Comment by briedel** [comment]
Generalizing the cleanup code is hard. It heavily depends on how the batch system reports the jobs ids and how the temp directory is setup. Do you have a good solution?

**Comment by dsschult** [comment]
Maybe move the cleanup code into the submit classes?

**Comment by briedel** [comment]
How is submitting relate to cleanup after a job is complete? One could keep a list of jobs id that were submitted and the time they were submitted. Once they hit the walltime the folder will be deleted

**Comment by dsschult** [comment]
They're related in that they both interact with the local batch system.  vs client.py is abstracted away from that.

**Comment by briedel** [comment]
Okay, adding it to `submit()` after all the jobs have been submitted might be the better solution in that case.

**Comment by briedel** [comment]
I realize. It should happen either before or after `submit()` submits the jobs. The best option may be to make it a function inside the `Submitxxx` class and let it be called from `client.py`

**Comment by dsschult** [comment]
missing a default cleanup (no-op) on the main Submit class.  otherwise looks good.

**Comment by briedel** [comment]
Added

**Pull request merged**
